"""Feature parity registry.

Each entry maps a ManageEngine-equivalent capability onto:
- the TenantGuard 365 module that owns it,
- the Microsoft API source it depends on,
- the permissions / licences required,
- the current implementation status,
- the security posture for the action.

Keep entries declarative and small — the registry is read by both the API
(/api/catalog/features) and the docs generator. Adding a feature here makes
it appear in the UI catalog automatically.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

# ---------------------------------------------------------------- enums

Module = Literal[
    "platform",
    "reports",
    "audit",
    "entra",
    "exchange",
    "onedrive",
    "sharepoint",
    "teams",
    "security",
    "compliance",
    "service_health",
    "management",
    "content_search",
    "remediation",
    "delegation",
    "powerbi",
    "yammer",
]

FeatureStatus = Literal[
    "implemented_real_api",
    "implemented_mock_only",
    "framework_ready",
    "needs_graph_permission",
    "needs_purview",
    "needs_defender",
    "needs_exchange_powershell",
    "needs_sharepoint_api_validation",
    "blocked_by_microsoft_api",
    "future_module",
    "deprecated_or_unsupported",
]

Priority = Literal["MVP", "Phase 2", "Phase 3", "Future"]

RiskLevel = Literal["low", "medium", "high", "critical"]

ExportFormat = Literal["CSV", "XLSX", "PDF", "HTML"]


# ---------------------------------------------------------------- entry


@dataclass(frozen=True, slots=True)
class FeatureEntry:
    key: str
    area: str
    name: str
    description: str
    module: Module
    status: FeatureStatus
    priority: Priority

    # Microsoft data source
    source: str = ""  # "Graph v1.0", "Graph beta", "Exchange PS", "Purview", "Defender"
    endpoint: str = ""  # path or family
    delegated_scopes: tuple[str, ...] = ()
    application_scopes: tuple[str, ...] = ()
    entra_role: str = ""
    other_role: str = ""  # Purview, Defender, Exchange admin role names
    license_dep: str = ""

    # Implementation surface
    ui_page: str = ""
    backend_service: str = ""
    database_tables: tuple[str, ...] = ()
    real_api: Literal["yes", "no", "partial", "unknown"] = "no"
    mock_supported: bool = True

    # Posture
    risk: RiskLevel = "low"
    requires_approval: bool = False
    requires_dry_run: bool = False
    audited: bool = True
    export_formats: tuple[ExportFormat, ...] = ()
    schedulable: bool = False
    alertable: bool = False

    # Operational
    gaps: str = ""
    next_action: str = ""
    tags: tuple[str, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------- entries

# Helper to keep declarations terse.
def _f(**kw: object) -> FeatureEntry:
    """Compact constructor — keep entry declarations terse."""
    return FeatureEntry(**kw)  # type: ignore[arg-type]


_PLATFORM: list[FeatureEntry] = [
    _f(
        key="platform.dashboard.overview",
        area="Platform",
        name="Central overview dashboard",
        description="Single landing page with health, latest audit, posture summary.",
        module="platform",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/",
        backend_service="me_routes",
        real_api="yes",
        export_formats=(),
        risk="low",
    ),
    _f(
        key="platform.dashboard.widgets",
        area="Platform",
        name="Add reports as dashboard widgets",
        description="Pin report runs / chart fragments to the home dashboard.",
        module="platform",
        status="framework_ready",
        priority="Phase 2",
        ui_page="/",
        next_action="Add `dashboard_widgets` table + reorderable widget host.",
    ),
    _f(
        key="platform.audit.technician",
        area="Platform",
        name="Technician audit trail",
        description="Append-only log of every admin/operator action on the platform.",
        module="audit",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/audit",
        backend_service="audit_routes",
        database_tables=("technician_audit_log",),
        real_api="yes",
        export_formats=("CSV", "XLSX"),
        risk="low",
        audited=True,
        next_action="Add Postgres RLS append-only role (P29 OPEN).",
    ),
    _f(
        key="platform.rbac.builtin",
        area="Platform",
        name="Built-in roles",
        description="Super Admin, Platform Admin, Security Admin, Auditor, Helpdesk, Read-only.",
        module="platform",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/delegation",
        backend_service="rbac_routes",
        database_tables=("platform_roles", "platform_permissions"),
        real_api="yes",
    ),
    _f(
        key="platform.rbac.custom",
        area="Platform",
        name="Custom roles + permission matrix UI",
        description="Compose roles from atomic permissions; assign with scope expressions.",
        module="platform",
        status="framework_ready",
        priority="Phase 2",
        ui_page="/delegation",
        next_action="Add CRUD UI for role-permission editing; backend already supports it.",
    ),
    _f(
        key="platform.delegation.scoped",
        area="Platform",
        name="Domain / attribute / virtual-tenant delegation",
        description="Scope a role assignment to a domain, attribute, or virtual tenant.",
        module="delegation",
        status="framework_ready",
        priority="Phase 2",
        next_action="Wire scope_meta enforcement into permission dependencies.",
    ),
    _f(
        key="platform.health.system",
        area="Platform",
        name="System health page",
        description="DB / Redis / OpenSearch / MinIO health + recent job stats.",
        module="service_health",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/system-health",
        backend_service="system_routes",
        real_api="yes",
        alertable=True,
    ),
    _f(
        key="platform.notifications.framework",
        area="Platform",
        name="Notification routing",
        description="Severity-based routing to email + Teams webhook + generic webhook.",
        module="platform",
        status="framework_ready",
        priority="Phase 2",
        ui_page="/notifications",
        gaps="Send pipeline + notification_events table not yet implemented.",
        next_action="Implement SMTP send + webhook dispatch + history table.",
    ),
    _f(
        key="platform.retention.policy",
        area="Platform",
        name="Data retention policy",
        description="Per-data-class retention windows + nightly cleanup jobs.",
        module="platform",
        status="framework_ready",
        priority="Phase 2",
        ui_page="/settings/retention",
        next_action="Add `retention_policy` row + scheduled cleanup tasks.",
    ),
    _f(
        key="platform.export.framework",
        area="Platform",
        name="Export framework (CSV/XLSX/PDF/HTML)",
        description="Streamed exports to MinIO with signed-URL retrieval.",
        module="reports",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/exports",
        backend_service="reports_routes",
        database_tables=("report_exports",),
        real_api="yes",
        export_formats=("CSV", "XLSX", "PDF", "HTML"),
        risk="medium",
        audited=True,
    ),
    _f(
        key="platform.scheduled.reports",
        area="Platform",
        name="Scheduled reports + email delivery",
        description="Cron-style schedules with email/webhook delivery.",
        module="reports",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/reports/scheduled",
        database_tables=("scheduled_reports",),
        real_api="yes",
        schedulable=True,
    ),
]


# ---------------- Entra ID reports + auditing
_ENTRA: list[FeatureEntry] = [
    _f(
        key="entra.users.all",
        area="Entra ID — Users",
        name="All users report",
        description="Inventory of every Entra user with key attributes.",
        module="entra",
        status="implemented_real_api",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/users",
        application_scopes=("User.Read.All",),
        ui_page="/entra/users",
        database_tables=("m365_users",),
        real_api="yes",
        export_formats=("CSV", "XLSX"),
        schedulable=True,
    ),
    _f(
        key="entra.users.guests",
        area="Entra ID — Users",
        name="Guest users report",
        description="External (#EXT#) users with last sign-in.",
        module="entra",
        status="implemented_real_api",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/users?$filter=userType eq 'Guest'",
        application_scopes=("User.Read.All",),
        ui_page="/entra/users",
        real_api="yes",
    ),
    _f(
        key="entra.users.inactive",
        area="Entra ID — Users",
        name="Inactive users",
        description="Users without sign-in in N days.",
        module="entra",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph beta",
        endpoint="/users + /reports/getOffice365ActiveUserDetail",
        application_scopes=("AuditLog.Read.All",),
        license_dep="Entra ID P1",
    ),
    _f(
        key="entra.users.deleted",
        area="Entra ID — Users",
        name="Deleted users",
        description="Soft-deleted users still within the 30-day restore window.",
        module="entra",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/directory/deletedItems/microsoft.graph.user",
        application_scopes=("User.Read.All",),
    ),
    _f(
        key="entra.groups.inventory",
        area="Entra ID — Groups",
        name="Group inventory",
        description="Security + M365 + Distribution groups.",
        module="entra",
        status="implemented_mock_only",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/groups",
        application_scopes=("Group.Read.All",),
        ui_page="/entra/groups",
    ),
    _f(
        key="entra.groups.empty",
        area="Entra ID — Groups",
        name="Empty groups",
        description="Groups with zero members.",
        module="entra",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/groups + /groups/{id}/members/$count",
        application_scopes=("Group.Read.All",),
    ),
    _f(
        key="entra.roles.assignments",
        area="Entra ID — Roles",
        name="Directory role assignments",
        description="Active directory-role members. Highlight privileged roles.",
        module="entra",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/directoryRoles",
        application_scopes=("RoleManagement.Read.Directory",),
        ui_page="/entra/roles",
    ),
    _f(
        key="entra.licenses.usage",
        area="Entra ID — Licenses",
        name="License usage",
        description="SKU consumed vs purchased; over-provisioning detection.",
        module="entra",
        status="implemented_real_api",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/subscribedSkus",
        application_scopes=("Organization.Read.All",),
        ui_page="/entra/licenses",
    ),
    _f(
        key="entra.signins.recent",
        area="Entra ID — Sign-ins",
        name="Recent sign-ins + risk",
        description="Last 30 days of sign-in events with risk classification.",
        module="entra",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/auditLogs/signIns",
        application_scopes=("AuditLog.Read.All",),
        license_dep="Entra ID P1 (for risk fields)",
        ui_page="/entra/signins",
        alertable=True,
    ),
    _f(
        key="entra.audit.directory",
        area="Entra ID — Audit",
        name="Directory audit",
        description="User/group/app changes from the directory audit log.",
        module="entra",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/auditLogs/directoryAudits",
        application_scopes=("AuditLog.Read.All",),
        ui_page="/entra/audit",
    ),
    _f(
        key="entra.users.mfa",
        area="Entra ID — Security",
        name="MFA / authentication method registration",
        description="Per-user authentication methods registered.",
        module="entra",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph beta",
        endpoint="/reports/authenticationMethods/userRegistrationDetails",
        application_scopes=("AuditLog.Read.All", "UserAuthenticationMethod.Read.All"),
    ),
    _f(
        key="entra.password.status",
        area="Entra ID — Security",
        name="Password expiry status",
        description="Users with passwords near expiry or expired.",
        module="entra",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/users?$select=passwordPolicies,lastPasswordChangeDateTime",
        application_scopes=("User.Read.All",),
    ),
]


# ---------------- Exchange Online
_EXCHANGE: list[FeatureEntry] = [
    _f(
        key="exchange.mailboxes.inventory",
        area="Exchange — Mailboxes",
        name="Mailbox inventory",
        description="All mailboxes with size, item count, type.",
        module="exchange",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0 + /reports",
        endpoint="/users/{id}/mailboxSettings + /reports/getMailboxUsageDetail",
        application_scopes=("MailboxSettings.Read", "Reports.Read.All"),
        ui_page="/exchange/mailboxes",
        export_formats=("CSV", "XLSX"),
    ),
    _f(
        key="exchange.mailboxes.size_quota",
        area="Exchange — Mailboxes",
        name="Mailbox size vs quota",
        description="Highlights mailboxes near or over quota.",
        module="exchange",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/reports/getMailboxUsageQuotaStatusMailboxCounts",
        application_scopes=("Reports.Read.All",),
    ),
    _f(
        key="exchange.mailboxes.inactive",
        area="Exchange — Mailboxes",
        name="Inactive mailboxes consuming licenses",
        description="Licensed users with no mailbox activity in N days.",
        module="exchange",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/reports/getOffice365ActiveUserDetail",
        application_scopes=("Reports.Read.All",),
    ),
    _f(
        key="exchange.mail.traffic",
        area="Exchange — Mail traffic",
        name="Mail traffic + top senders/recipients",
        description="Aggregate inbound/outbound traffic with top senders.",
        module="exchange",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/reports/getEmailActivityCounts + getMailboxUsageDetail",
        application_scopes=("Reports.Read.All",),
    ),
    _f(
        key="exchange.mail.spam_malware",
        area="Exchange — Threat",
        name="Spam / malware detection",
        description="EOP detections per recipient.",
        module="exchange",
        status="needs_defender",
        priority="Phase 2",
        source="Defender / Graph beta",
        endpoint="/security/threatSubmissions",
        application_scopes=("ThreatSubmission.Read.All",),
        license_dep="Defender for Office 365",
    ),
    _f(
        key="exchange.permissions.full_access",
        area="Exchange — Permissions",
        name="Mailbox FullAccess / SendAs / SendOnBehalfOf",
        description="Non-owner delegation. SendAs is highlighted critical.",
        module="exchange",
        status="needs_exchange_powershell",
        priority="MVP",
        source="Exchange Online PowerShell",
        endpoint="Get-MailboxPermission / Get-RecipientPermission",
        other_role="Exchange Administrator",
        ui_page="/exchange/permissions",
        risk="high",
    ),
    _f(
        key="exchange.forwarding.external",
        area="Exchange — Risk",
        name="External forwarding rules",
        description="Inbox rules + transport rules that forward mail outside the tenant.",
        module="exchange",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/users/{id}/messageRules",
        application_scopes=("MailboxSettings.Read",),
        ui_page="/exchange/forwarding-risk",
        risk="critical",
        alertable=True,
    ),
    _f(
        key="exchange.mobile.devices",
        area="Exchange — Mobile",
        name="Mobile / ActiveSync device inventory",
        description="Per-user ActiveSync devices, OS, policy compliance.",
        module="exchange",
        status="needs_exchange_powershell",
        priority="Phase 2",
        source="Exchange Online PowerShell",
        endpoint="Get-MobileDevice",
        other_role="Exchange Administrator",
    ),
    _f(
        key="exchange.litigation_hold",
        area="Exchange — Compliance",
        name="Litigation + in-place hold reports",
        description="Mailboxes with hold enabled and owner.",
        module="exchange",
        status="needs_exchange_powershell",
        priority="Phase 2",
        source="Exchange Online PowerShell",
        endpoint="Get-Mailbox (LitigationHoldEnabled)",
        other_role="Exchange Administrator",
        license_dep="Exchange Plan 2 / E5",
    ),
    _f(
        key="exchange.owa.policies",
        area="Exchange — OWA",
        name="OWA mailbox policies + logon",
        description="OWA logon by user/browser/OS where available.",
        module="exchange",
        status="needs_exchange_powershell",
        priority="Phase 3",
        source="Exchange Online PowerShell",
        endpoint="Get-OwaMailboxPolicy",
    ),
    _f(
        key="exchange.public_folders",
        area="Exchange — Public folders",
        name="Public folder reports",
        description="Inventory, sizes, mail-enabled flag.",
        module="exchange",
        status="needs_exchange_powershell",
        priority="Phase 3",
        source="Exchange Online PowerShell",
        endpoint="Get-PublicFolder / Get-MailPublicFolder",
    ),
    # auditing
    _f(
        key="exchange.audit.owner",
        area="Exchange — Audit",
        name="Mailbox owner / non-owner / delegate access",
        description="Audit events from Unified Audit Log for mailbox access.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/auditLogs/directoryAudits + /security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
    _f(
        key="exchange.audit.admin",
        area="Exchange — Audit",
        name="Exchange admin activities",
        description="Mailbox create/delete/permission/property changes by admins.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
]


# ---------------- OneDrive
_ONEDRIVE: list[FeatureEntry] = [
    _f(
        key="onedrive.accounts",
        area="OneDrive — Inventory",
        name="OneDrive accounts",
        description="Per-user storage, file count, last activity.",
        module="onedrive",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/reports/getOneDriveUsageAccountDetail",
        application_scopes=("Reports.Read.All",),
        ui_page="/onedrive/accounts",
    ),
    _f(
        key="onedrive.sharing",
        area="OneDrive — Sharing",
        name="OneDrive sharing audit",
        description="External + anonymous links from user OneDrives.",
        module="onedrive",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/drives/{id}/items + /permissions",
        application_scopes=("Files.Read.All",),
        ui_page="/onedrive/sharing",
        risk="high",
    ),
    _f(
        key="onedrive.audit.files",
        area="OneDrive — Audit",
        name="File create / modify / delete / move / rename / restore",
        description="UAL file events for OneDrive.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
    _f(
        key="onedrive.audit.sync",
        area="OneDrive — Audit",
        name="Sync device events",
        description="Allowed/blocked sync devices, IP + device name.",
        module="audit",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
]


# ---------------- SharePoint Online
_SHAREPOINT: list[FeatureEntry] = [
    _f(
        key="sharepoint.sites.inventory",
        area="SharePoint — Sites",
        name="Site inventory",
        description="All sites with template, owner, last activity, storage.",
        module="sharepoint",
        status="implemented_real_api",
        priority="MVP",
        source="Graph v1.0 + /reports",
        endpoint="/sites + /reports/getSharePointSiteUsageDetail",
        application_scopes=("Sites.Read.All", "Reports.Read.All"),
        ui_page="/sharepoint/sites",
    ),
    _f(
        key="sharepoint.sites.external_sharing",
        area="SharePoint — Sharing",
        name="External-sharing-enabled sites",
        description="Sites where external sharing is permitted.",
        module="sharepoint",
        status="needs_sharepoint_api_validation",
        priority="MVP",
        source="SharePoint REST + Graph",
        endpoint="/sites/{id}/settings",
        application_scopes=("Sites.FullControl.All",),
        risk="high",
    ),
    _f(
        key="sharepoint.permissions.matrix",
        area="SharePoint — Permissions",
        name="Permission matrix (effective)",
        description="Effective principals per resource. External + anonymous flagged.",
        module="sharepoint",
        status="implemented_mock_only",
        priority="MVP",
        source="Graph v1.0",
        endpoint=(
            "/sites/{id}/permissions + lists/{id}/items"
            "?$expand=fields,hasUniqueRoleAssignments"
        ),
        application_scopes=("Sites.FullControl.All",),
        ui_page="/sharepoint/permissions",
        risk="high",
    ),
    _f(
        key="sharepoint.sharing.links",
        area="SharePoint — Sharing",
        name="Sharing links",
        description="Anonymous / organisation / specific-people links with expiry.",
        module="sharepoint",
        status="needs_sharepoint_api_validation",
        priority="MVP",
        source="Graph beta",
        endpoint="/sites/{id}/lists/{id}/items/{id}/permissions",
        application_scopes=("Sites.FullControl.All",),
        ui_page="/sharepoint/sharing-links",
        risk="critical",
    ),
    _f(
        key="sharepoint.external.users",
        area="SharePoint — Sharing",
        name="External users + last access",
        description="Guests with site access. Stale guests flagged.",
        module="sharepoint",
        status="needs_sharepoint_api_validation",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/sites/{id}/permissions + invitedUser",
        application_scopes=("Sites.FullControl.All",),
        ui_page="/sharepoint/external-users",
        risk="high",
    ),
    _f(
        key="sharepoint.broken_inheritance",
        area="SharePoint — Permissions",
        name="Broken-inheritance items",
        description="Items + folders with unique permissions (inheritance break).",
        module="sharepoint",
        status="needs_sharepoint_api_validation",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/sites/{id}/lists/{id}/items?$filter=hasUniqueRoleAssignments eq true",
        application_scopes=("Sites.FullControl.All",),
        ui_page="/sharepoint/broken-inheritance",
    ),
    _f(
        key="sharepoint.audit.file_ops",
        area="SharePoint — Audit",
        name="File access / modify / delete / move / rename / restore",
        description="UAL events for SharePoint files.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
    _f(
        key="sharepoint.audit.sharing_ops",
        area="SharePoint — Audit",
        name="Sharing invitation / link create / accept / revoke",
        description="UAL events for share-link lifecycle.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
    _f(
        key="sharepoint.mgmt.permissions",
        area="SharePoint — Management",
        name="Add / remove / modify site permissions (dry-run)",
        description="Bulk permission ops with dry-run + approval workflow.",
        module="management",
        status="framework_ready",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="POST /sites/{id}/permissions",
        application_scopes=("Sites.FullControl.All",),
        risk="critical",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="sharepoint.mgmt.groups",
        area="SharePoint — Management",
        name="Manage site groups (create / delete / membership)",
        description="Bulk operations with dry-run + approval.",
        module="management",
        status="framework_ready",
        priority="Phase 3",
        source="SharePoint REST",
        endpoint="/web/sitegroups",
        risk="critical",
        requires_approval=True,
        requires_dry_run=True,
    ),
]


# ---------------- Teams
_TEAMS: list[FeatureEntry] = [
    _f(
        key="teams.inventory",
        area="Teams — Inventory",
        name="Team + channel inventory",
        description="All Teams with channels, members, owners, guests.",
        module="teams",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/teams + /teams/{id}/channels + /teams/{id}/members",
        application_scopes=("Team.ReadBasic.All", "Channel.ReadBasic.All", "TeamMember.Read.All"),
        ui_page="/teams/inventory",
    ),
    _f(
        key="teams.usage",
        area="Teams — Usage",
        name="Activity / device usage",
        description="Active users, devices, messages per period.",
        module="teams",
        status="needs_graph_permission",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="/reports/getTeamsUserActivityUserDetail",
        application_scopes=("Reports.Read.All",),
    ),
    _f(
        key="teams.audit.lifecycle",
        area="Teams — Audit",
        name="Team / channel create / delete / setting change",
        description="UAL events for Teams lifecycle.",
        module="audit",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        application_scopes=("AuditLog.Read.All",),
    ),
    _f(
        key="teams.mgmt.create_team",
        area="Teams — Management",
        name="Create / update / delete teams (dry-run)",
        description="Bulk team management with approval.",
        module="management",
        status="framework_ready",
        priority="Phase 3",
        source="Graph v1.0",
        endpoint="POST /teams",
        application_scopes=("Team.Create", "TeamSettings.ReadWrite.All"),
        risk="high",
        requires_approval=True,
        requires_dry_run=True,
    ),
]


# ---------------- Service health
_SERVICE_HEALTH: list[FeatureEntry] = [
    _f(
        key="service_health.overview",
        area="Service health",
        name="Service health overview + incidents",
        description="M365 service status + advisories from Microsoft.",
        module="service_health",
        status="implemented_real_api",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/admin/serviceAnnouncement/healthOverviews + /issues + /messages",
        application_scopes=("ServiceHealth.Read.All", "ServiceMessage.Read.All"),
        ui_page="/service-health",
        alertable=True,
    ),
]


# ---------------- Security / compliance
_SECURITY: list[FeatureEntry] = [
    _f(
        key="security.alerts.list",
        area="Security — Alerts",
        name="Security alerts",
        description="Aggregated alerts from Microsoft + internal rules.",
        module="security",
        status="needs_graph_permission",
        priority="MVP",
        source="Graph v1.0",
        endpoint="/security/alerts_v2",
        application_scopes=("SecurityEvents.Read.All", "SecurityAlert.Read.All"),
        ui_page="/security/alerts",
        alertable=True,
    ),
    _f(
        key="security.rules.internal",
        area="Security — Rules",
        name="Internal rule engine",
        description="Pattern-based detections evaluated server-side.",
        module="security",
        status="implemented_real_api",
        priority="MVP",
        ui_page="/security/rules",
        backend_service="security.rules",
    ),
    _f(
        key="security.investigations.cases",
        area="Security — Investigations",
        name="Investigation cases",
        description="Linked alerts, timeline, notes, analyst assignment.",
        module="security",
        status="framework_ready",
        priority="Phase 2",
        ui_page="/security/investigations",
    ),
    _f(
        key="security.content_search.profiles",
        area="Security — Content search",
        name="Content search profiles + scheduled runs",
        description="Pattern / regex / common-phrase searches over mail + sites.",
        module="content_search",
        status="needs_purview",
        priority="Phase 3",
        source="Purview eDiscovery (Graph beta)",
        endpoint="/security/cases/ediscoveryCases",
        application_scopes=("eDiscovery.Read.All",),
        other_role="Purview — eDiscovery Manager",
        license_dep="Purview / E5 Compliance",
        ui_page="/content-search",
        risk="critical",
        requires_approval=True,
        audited=True,
    ),
    _f(
        key="security.remediation.policies",
        area="Security — Remediation",
        name="Auto-remediation policies (dry-run)",
        description="Suspicious user/mailbox activity policies — dry-run only by default.",
        module="remediation",
        status="framework_ready",
        priority="Phase 3",
        ui_page="/remediation",
        risk="critical",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="security.dlp.alerts",
        area="Compliance — DLP",
        name="DLP alerts",
        description="Data-loss-prevention rule hits.",
        module="compliance",
        status="needs_purview",
        priority="Phase 2",
        source="Purview / Graph beta",
        endpoint="/security/dataLossPrevention",
        license_dep="Purview DLP",
    ),
    _f(
        key="security.defender.hunting",
        area="Security — Defender",
        name="Defender advanced hunting",
        description="Run KQL hunting queries.",
        module="security",
        status="needs_defender",
        priority="Phase 3",
        source="Defender API",
        endpoint="/api/advancedhunting/run",
        license_dep="Defender for Endpoint / O365 P2",
    ),
]


# ---------------- Power BI / Yammer
_OTHER: list[FeatureEntry] = [
    _f(
        key="powerbi.audit.dashboards",
        area="Power BI — Audit",
        name="Dashboard / report lifecycle audit",
        description="Dashboard + report create / view / share / export events.",
        module="powerbi",
        status="needs_graph_permission",
        priority="Phase 3",
        source="Graph beta",
        endpoint="/security/auditLog/queries (Power BI workload)",
        application_scopes=("AuditLog.Read.All",),
        license_dep="Power BI Pro",
    ),
    _f(
        key="yammer.usage",
        area="Viva Engage — Usage",
        name="Viva Engage usage + audit",
        description="Activity + audit. Limited Graph coverage today.",
        module="yammer",
        status="needs_graph_permission",
        priority="Future",
        source="Graph beta (limited)",
        endpoint="/reports/getYammerActivityUserDetail (deprecated)",
        gaps="Microsoft is migrating Yammer audit to Viva Engage; APIs in flux.",
    ),
    _f(
        key="powerbi.audit.subscriptions",
        area="Power BI — Audit",
        name="Trial subscriptions, content packs, admin portal",
        description="Power BI admin-level activity.",
        module="powerbi",
        status="needs_graph_permission",
        priority="Phase 3",
        source="Graph beta",
        endpoint="/security/auditLog/queries",
        license_dep="Power BI Pro",
    ),
]


# ---------------- Management actions
_MANAGEMENT: list[FeatureEntry] = [
    _f(
        key="management.entra.password_reset",
        area="Management — Entra",
        name="Reset password (dry-run)",
        description="Bulk password reset with approval.",
        module="management",
        status="framework_ready",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="POST /users/{id}/authentication/methods/{id}/resetPassword",
        application_scopes=("UserAuthenticationMethod.ReadWrite.All",),
        risk="high",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.entra.block_user",
        area="Management — Entra",
        name="Block / unblock user (dry-run)",
        description="Toggle accountEnabled with approval.",
        module="management",
        status="framework_ready",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="PATCH /users/{id} {accountEnabled:false}",
        application_scopes=("User.ReadWrite.All",),
        risk="high",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.entra.licenses",
        area="Management — Entra",
        name="Assign / remove licenses (dry-run)",
        description="Bulk SKU assignment with approval.",
        module="management",
        status="framework_ready",
        priority="Phase 2",
        source="Graph v1.0",
        endpoint="POST /users/{id}/assignLicense",
        application_scopes=("User.ReadWrite.All",),
        risk="medium",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.exchange.mailbox_attrs",
        area="Management — Exchange",
        name="Modify mailbox attributes (dry-run)",
        description="SMTP / proxy / IMAP / MAPI / POP / OWA / EWS toggles.",
        module="management",
        status="needs_exchange_powershell",
        priority="Phase 3",
        source="Exchange Online PowerShell",
        endpoint="Set-Mailbox / Set-CASMailbox",
        other_role="Exchange Administrator",
        risk="high",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.exchange.forwarding",
        area="Management — Exchange",
        name="Configure mail forwarding (dry-run)",
        description="Set/clear forwardingSmtpAddress + DeliverToMailboxAndForward.",
        module="management",
        status="needs_exchange_powershell",
        priority="Phase 3",
        source="Exchange Online PowerShell",
        endpoint="Set-Mailbox -ForwardingSmtpAddress",
        risk="critical",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.exchange.auto_reply",
        area="Management — Exchange",
        name="Configure internal / external auto-reply",
        description="Out-of-office settings bulk-applied with approval.",
        module="management",
        status="needs_graph_permission",
        priority="Phase 3",
        source="Graph v1.0",
        endpoint="PATCH /users/{id}/mailboxSettings/automaticRepliesSetting",
        application_scopes=("MailboxSettings.ReadWrite",),
        risk="medium",
        requires_approval=True,
        requires_dry_run=True,
    ),
    _f(
        key="management.exchange.litigation_hold",
        area="Management — Exchange",
        name="Activate litigation hold",
        description="Enable + set duration + owner.",
        module="management",
        status="needs_exchange_powershell",
        priority="Phase 3",
        source="Exchange Online PowerShell",
        endpoint="Set-Mailbox -LitigationHoldEnabled",
        other_role="Exchange Administrator",
        license_dep="Exchange Plan 2 / E5",
        risk="high",
        requires_approval=True,
        requires_dry_run=True,
    ),
]


# ---------------- assemble

FEATURES: list[FeatureEntry] = [
    *_PLATFORM,
    *_ENTRA,
    *_EXCHANGE,
    *_ONEDRIVE,
    *_SHAREPOINT,
    *_TEAMS,
    *_SERVICE_HEALTH,
    *_SECURITY,
    *_OTHER,
    *_MANAGEMENT,
]


def features_by_module() -> dict[str, list[FeatureEntry]]:
    out: dict[str, list[FeatureEntry]] = {}
    for f in FEATURES:
        out.setdefault(f.module, []).append(f)
    return out


def feature_summary() -> dict[str, int]:
    """High-level counts by status. Cheap, deterministic."""
    counts: dict[str, int] = {}
    for f in FEATURES:
        counts[f.status] = counts.get(f.status, 0) + 1
    return counts
